menu:
#  About: /about
  Archives: /archives
#  RSS: /atom.xml

widgets:
#- search
#- recent_posts
- category
#- tagcloud

excerpt_link: 阅读全文 ››

twitter:
  username:
  show_replies: false
  tweet_count: 1

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
