menu:
#  About: /about
  Archives: /archives
#  RSS: /atom.xml

widgets:
#- search
#- recent_posts
- category
#- tagcloud

excerpt_link: 阅读全文 ››

twitter:
  username:
  show_replies: false
  tweet_count: 0

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

google_analytics:
